### DISCUSSION TITLE
Set individual Volume in Group

### DISCUSSION THREAD

**Discussion by blackmore190** [B5r1oJ0A9G/teufel_raumfeld#15] [Q&A] [answered]
Hi, 

is it possible to adjust the individual volume in a group of the speakers? 
e.g. a Group of 3 devices (Kitchen, LivingRoom and TV) so the group is active and i want to change the volume to:
kitchen = 30
LivingRoom = 23
TV= 16

Is that possible? If so: how? 

My current idea is to ungroup, set volume and switch then the group back on. But I'm not pretty statisfied by this workaround. 

Thanks for your help!

**Comment by B5r1oJ0A9G** [comment, marked as answer]
I guess what you're seeking for is ```teufel_raumfeld.abs_volume_set```. Its main purpose is to set the volume of all speakers in a group to an absolute volume. But it also supports an optional parameter for a room or a list of room names to set the absolute volume only to this resp. to them.

In the following example, first the volume of all speakers in a speaker group is set to 30% and then the volume of the Kitchen speaker is set to 20%.

```yaml
alias: Reset volume of Living room, Dining & Kitchen speakers
sequence:
  - service: teufel_raumfeld.abs_volume_set
    data:
      volume_level: 0.3
    entity_id: media_player.group_dining_kitchen_livingroom
  - service: teufel_raumfeld.abs_volume_set
    data:
      volume_level: 0.2
      rooms: Kitchen
    entity_id: media_player.group_dining_kitchen_livingroom
mode: single
```
