### DISCUSSION TITLE
How to realize a radio station rotation

### DISCUSSION THREAD

**Discussion by ulilicht** [B5r1oJ0A9G/teufel_raumfeld#43] [Q&A] [answered]
Hi there, 

I'm currently exploring controlling radio stations on Raumfeld speakers through an [Ikea Styrbar](https://www.golem.de/2105/156481-273172-273169.jpg) controller with two buttons, left and right. 

**My goal:** 
We usually listen to around 4 different radio stations. I'd like to rotate through them. 

**Desired behavior:** 
If no music is playing, click "next" and start with first radio station. 
If music is already playing, click "next" and play the next radio station. 
If music is already playing, click "previous" and play the previous radio station. 

--> rotate forward and backwards through 4 predefined stations like this. 

**How would you realize this?** 
I was thinking about an *.m3u playlist which contains the 4 stations, but Raumfeld seems not to be able to play the m3u file. 

Thanks for your ideas!

**Comment by ulilicht** [comment, marked as answer]
For anyone working on something similar: 

I have for now realized the described functionality through Raumfeld Playlists. 

- Create a playlist in the Raumfeld App (on a radio station, Burger Menu, add to Teufel Playlist) 
- When playing through home assistant, select the playlist instead of the item. 


There is still one open issue related to Spotify (integration has some issues, see [#4](https://github.com/B5r1oJ0A9G/teufel_raumfeld/issues/4#issuecomment-1407604743) ) but in general it works well. 


For reference, if anyone needs something similar, here is the "Press Next Button" automation YAML: 

```
alias: StyrbarNext
description: ""
trigger:
  - device_id: 04bd5d7279192dbd3ec506a23b59e105
    domain: deconz
    platform: device
    type: remote_button_short_release
    subtype: right
condition: []
action:
  - service: teufel_raumfeld.set_power_state
    data:
      entity_id: sensor.room_wohnzimmer_powerstate
      power_state: "on"
  - service: teufel_raumfeld.play_sound
    data:
      entity_id: media_player.room_wohnzimmer
  - if:
      - condition: state
        entity_id: media_player.room_wohnzimmer
        state: playing
    then:
      - service: media_player.media_next_track
        data: {}
        target:
          entity_id: media_player.room_wohnzimmer
    else:
      - service: media_player.play_media
        target:
          entity_id: media_player.room_wohnzimmer
        data:
          media_content_id: >-
            0/Playlists/MyPlaylists/Styrbar[:sep:]dlna-playcontainer://uuid%3Ad0bb4d3f-ede7-46cc-8ae8-71bf9a07d9b1?sid=urn%3Aupnp-org%3AserviceId%3AContentDirectory&cid=0%2FPlaylists%2FMyPlaylists%2FStyrbar&md=0
          media_content_type: object.container.playlistContainer
        metadata:
          title: Styrbar
          thumbnail: null
          media_class: music
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: object.container
              media_content_id: 0/Playlists[:sep:]0/Playlists
            - media_content_type: object.container
              media_content_id: 0/Playlists/MyPlaylists[:sep:]0/Playlists/MyPlaylists
mode: single

```


And the Play Previous: 

```
alias: StyrbarPrevious
description: ""
trigger:
  - device_id: 04bd5d7279192dbd3ec506a23b59e105
    domain: deconz
    platform: device
    type: remote_button_short_release
    subtype: left
condition: []
action:
  - service: teufel_raumfeld.set_power_state
    data:
      entity_id: sensor.room_wohnzimmer_powerstate
      power_state: "on"
  - service: teufel_raumfeld.play_sound
    data:
      entity_id: media_player.room_wohnzimmer
  - if:
      - condition: state
        entity_id: media_player.room_wohnzimmer
        state: playing
    then:
      - service: media_player.media_previous_track
        data: {}
        target:
          entity_id: media_player.room_wohnzimmer
      - service: media_player.media_previous_track
        data: {}
        target:
          entity_id: media_player.room_wohnzimmer
    else:
      - service: media_player.play_media
        target:
          entity_id: media_player.room_wohnzimmer
        data:
          media_content_id: >-
            0/Playlists/MyPlaylists/Styrbar[:sep:]dlna-playcontainer://uuid%3Ad0bb4d3f-ede7-46cc-8ae8-71bf9a07d9b1?sid=urn%3Aupnp-org%3AserviceId%3AContentDirectory&cid=0%2FPlaylists%2FMyPlaylists%2FStyrbar&md=0
          media_content_type: object.container.playlistContainer
        metadata:
          title: Styrbar
          thumbnail: null
          media_class: music
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: object.container
              media_content_id: 0/Playlists[:sep:]0/Playlists
            - media_content_type: object.container
              media_content_id: 0/Playlists/MyPlaylists[:sep:]0/Playlists/MyPlaylists
mode: single

```
