### ISSUE TITLE
No device entities created

### ISSUE THREAD

**Issue by didericko** [B5r1oJ0A9G/teufel_raumfeld#2]
![image](https://user-images.githubusercontent.com/31383515/108167802-8a54a180-70f6-11eb-9fef-8a600513ffba.png)

Only the media-player entities are there.

**Comment by B5r1oJ0A9G** [comment]
I suspect the device name prefixes differ. With d4f7759 some logging is introduced. I'd be intersted in the log value for `raumfeld.wsd`. In particular in the `#text` values of items in the `device` list:

`[...]__init__.py->async_setup_entry: raumfeld.wsd={'devices': [...]('#text', '`**Raumfeld ConfigDevice**`')[...]`

Loglevel for teufel_raumfeld must be set to `debug` in configuration.yaml:

```
logger:
  default: warn
  logs:
    custom_components.teufel_raumfeld: debug
```
