### ISSUE TITLE
Set abs volume of a room in a group not working

### ISSUE THREAD

**Issue by JimboJones3101** [B5r1oJ0A9G/teufel_raumfeld#42]
Hi there,

I it's not an bug but I simply cannot figure out how to set the abs volume for a room within a group.

My setup is the following:

![image](https://user-images.githubusercontent.com/45816127/212037321-5c8aeb87-d775-4b18-92b5-092a90e7f388.png)

My script loooks like this: 
```
alias: Raumfeld normal
sequence:
  - service: teufel_raumfeld.abs_volume_set
    data:
      volume_level: 0.2
      entity_id: media_player.group_one_m_one_s
  - service: teufel_raumfeld.abs_volume_set
    data:
      volume_level: 0.3
      rooms: One S
      entity_id: media_player.room_one_s
mode: single
```

The volume is set to 20%, but the second call is not processed. I tried removing the attribute "rooms", but then the log tells me 

_2023-01-12 10:58:38.066 ERROR (MainThread) [homeassistant.components.script.raumfeld_lautstarke_normal] Raumfeld normal: Error executing script. Invalid data for call_service at pos 2: value must be one of ['One M', 'One S'] @ data['rooms'][0]_

When i change the attribute to the following

```
alias: Raumfeld normal
sequence:
  - service: teufel_raumfeld.abs_volume_set
    data:
      volume_level: 0.2
      entity_id: media_player.group_one_m_one_s
  - service: teufel_raumfeld.abs_volume_set
    data:
      volume_level: 0.3
      rooms: 'One S'
      entity_id: media_player.room_one_s
mode: single
```

I can see the following statement in the logs

_2023-01-12 11:05:02.967 DEBUG (MainThread) [custom_components.teufel_raumfeld] media_player.py->async_set_rooms_volume_level: Method was called although speaker group '['One S']' is invalid_

I assume I'm calling the wrong room, but how can I find out? Any suggestions of how to continue?
I can always change the volume of a group but not of a room.... :(

**Comment by JimboJones3101** [comment]
Yeah, 
I figured out the issue! 

For anybody suffering from the same topic:

You need to mention the specific room, but direct the servicecall to the group itself.

Instead of the above mentioned the correct way for this script is the following:

```
alias: Raumfeld normal
sequence:
  - service: teufel_raumfeld.abs_volume_set
    data:
      volume_level: 0.2
      entity_id: media_player.group_one_m_one_s
  - service: teufel_raumfeld.abs_volume_set
    data:
      volume_level: 0.3
      rooms: One S
      entity_id: media_player.group_one_m_one_s
mode: single
```
