### ISSUE TITLE
Question regarding playback

### ISSUE THREAD

**Issue by sajov** [B5r1oJ0A9G/teufel_raumfeld#76]
First of all thank you for this great Projekt which I’m really interested in.
I just wondering if it would be possible to have an automation to play Spotify on speaker and speaker groups?
I also would like to know where you got all this raumfeld API background information from?

**Comment by mathebox** [comment]
Have you already thought about combining this integration with the Spotify integration to achieve this? Here is a proof of concept (not fully tested) that turns on the speaker, sets the output destination (source) for Spotify, and starts playing a playlist.

```yaml
sequence:
  - action: select.select_option
    metadata: {}
    data:
      option: "on"
    target:
      entity_id: select.room_xxx_powerstate
  - action: media_player.select_source
    metadata: {}
    data:
      source: Kitchen
    target:
      entity_id: media_player.spotify_xxxx
  - action: media_player.play_media
    target:
      entity_id:
        - media_player.spotify_xxx
    data:
      media_content_id: >-
        https://open.spotify.com/playlist/5ddugJBHUWApO8ESkma7Ys
      media_content_type: playlist
alias: Spotify Test
description: ""

```
